# Simulation constants
SIMULATION_WIDTH = 250
SIMULATION_HEIGHT = 250
CAPTURE_DISTANCE = 1.0

# Evader constants
EVADER_RANDOM_MIN_SPEED = 1
EVADER_RANDOM_MAX_SPEED = 1.5
EVADER_ACCELERATION = 0.7

# Pursuer constants
PURSUER_RANDOM_MIN_SPEED = 0.8
PURSUER_RANDOM_MAX_SPEED = 1.7
PURSUER_ACCELERATION = 0.7

# Simulation run constants
MAX_STEPS_PER_EPISODE = 1000
MIN_PURSUERS = 1
MAX_PURSUERS = 5

# Visualization constants
EVADER_SIZE = 10
PURSUER_SIZE = 8
ANIMATION_INTERVAL = 50  # milliseconds
