# Simulation constants
SIMULATION_WIDTH = 500
SIMULATION_HEIGHT = 500
CAPTURE_DISTANCE = 1.0

# Evader constants
EVADER_MIN_SPEED = 0.8
EVADER_MAX_SPEED = 1.0
EVADER_ACCELERATION = 0.1

# Pursuer constants
PURSUER_MIN_SPEEDD = 0.6
PURSUER_MAX_SPEED = 0.8
PURSUER_ACCELERATION = 0.08

# Simulation run constants
MAX_STEPS_PER_EPISODE = 1000
MIN_PURSUERS = 1
MAX_PURSUERS = 5

# Visualization constants
EVADER_COLOR = 'red'
PURSUER_COLOR = 'blue'
EVADER_SIZE = 10
PURSUER_SIZE = 8
ANIMATION_INTERVAL = 50  # milliseconds
